### ISSUE TITLE
Homebrew reporting warning on `brew upgrade`

### ISSUE THREAD

**Issue by eksoparty** [universal-ctags/homebrew-universal-ctags#13] opened 2016-08-16 06:34 UTC
Warning: Calling 'depends_on :automake' is deprecated!
Use 'depends_on "automake"' instead.
/usr/local/Library/Taps/universal-ctags/homebrew-universal-ctags/universal-ctags.rb:5:in `class:UniversalCtags'
Please report this to the universal-ctags/universal-ctags tap!

**Comment by mikedfunk** [comment] 2016-08-20 01:48
+1

**Comment by lucafavatella** [comment] 2016-08-20 15:06
@xitkov I believe that PR #8 - merged 9 days ago - fixed this. May I suggest you re-test with a fresh version of the formula/tap and update this ticket?

**Comment by eksoparty** [comment] 2016-08-22 10:39
I had to do `brew untap universal-ctags/universal-ctags` and then `brew tap universal-ctags/universal-ctags` to fix it.

Is there a way to update the tap without re-tapping?

**Comment by cweagans** [comment] 2016-08-22 15:53
You should be able to `brew update` to get the latest formula. Did that not work?

**Comment by eksoparty** [comment] 2016-08-22 16:24
No, it did not work.

**Comment by thoughton** [comment] 2017-02-12 10:44
~~I may be wrong, but I think it's `brew upgrade` to make sure installed formulas are the latest.~~

Ah, please ignore me. I've just re-read the original issue and realised my comment was not helpful at all. Sorry!

**Comment by KazuakiM** [comment] 2017-03-18 04:00
Why is it open though the problem is solved?

**Closed as completed** 2017-07-17 10:31 UTC
